stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

include:
  template: Serverless.gitlab-ci.yml

test-page:
  stage: test
  image: node:12
  script:
    - yarn --cwd ./page
    - yarn --cwd ./page test:nowatch
    
test-server:
  stage: test
  image: node:12
  script:
    - yarn --cwd ./server
    - yarn --cwd ./server test

build:
  stage: build
  image: docker:19.03.12
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    
deploy_dev:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/gitlabktl:latest
  script:
  - /usr/bin/gitlabktl app deploy
  environment:
    name: dev
  only:
  - master

